### ISSUE TITLE
Support Hot-loading of Addons

### ISSUE THREAD

**Issue by BenWoodford** [FennecLabsLtd/VRUtilityBelt#13]
For loading in add-ons when they're enabled, without having to restart

**Comment by BenWoodford** [comment]
API works, but plugins will not be unloaded/reloaded without a restart, what with being DLLs and whatnot.

**Comment by bddckr** [comment]
If you load the DLLs into a new `AppDomain` you can unload the `AppDomain` which unloads the DLLs!
Only big issue is handling crashes in the DLL properly, so it doesn't crash the `AppDomain` in the main executable, thus preventing the DLLs to be unloadable.

If you only call into the plugins that's easily handled by try-catch'ing all the exceptions resulting in that call into the plugin. Otherwise there's an unhandled exception handler on the `AppDomain` which only leaves threading bugs as the ones that can prevent the hotreloading.

**Comment by BenWoodford** [comment]
They hook into things too much and do all sorts so it's unwise, and apparently even loading into their own `AppDomain` can be precarious at times.
